name: CI/CD Automated Deployment

on:
  push:
    branches: [ "principal" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/cesarivanhdezarroyo-maker/practica5-cloud:latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: "ghp_zXbtTomOZUxltBUsSlcae1DbDFB0tG1waB9L"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to AWS EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker stop my-node-app || true
            sudo docker rm my-node-app || true
            sudo docker pull ${{ env.IMAGE_NAME }}
            sudo docker run -d --name my-node-app -p 80:3000 ${{ env.IMAGE_NAME }}
